name: Check everything

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  checks:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Set up Dependencies
        run: |
          brew install llvm@18
          echo "/opt/homebrew/opt/llvm@18/bin" >> "$GITHUB_PATH"

      - name: Set up Odin
        run: |
          git clone https://github.com/odin-lang/Odin.git --depth 1 --single-branch --branch=master
          cd Odin
          make
          echo "$(pwd)" >> "$GITHUB_PATH"
          ./odin report

      - name: Check everything
        run: |
          FLAGS="-vet -strict-style -vet-tabs -disallow-do -warnings-as-errors"
          odin check sv.odin -file $FLAGS
          odin check cli.odin -file $FLAGS
